<?php

/**
 * Base class that represents a row from the 'asset' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Feb 27 09:27:30 2010
 *
 * @package    lib.model.om
 */
abstract class BaseAsset extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AssetPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the slug field.
	 * @var        string
	 */
	protected $slug;

	/**
	 * The value for the status field.
	 * @var        int
	 */
	protected $status;

	/**
	 * The value for the archive_id field.
	 * @var        int
	 */
	protected $archive_id;

	/**
	 * The value for the asset_type field.
	 * @var        int
	 */
	protected $asset_type;

	/**
	 * The value for the assigned_title field.
	 * @var        string
	 */
	protected $assigned_title;

	/**
	 * The value for the category_id field.
	 * @var        int
	 */
	protected $category_id;

	/**
	 * The value for the notes field.
	 * @var        string
	 */
	protected $notes;

	/**
	 * The value for the event_date field.
	 * @var        string
	 */
	protected $event_date;

	/**
	 * The value for the source_filename field.
	 * @var        string
	 */
	protected $source_filename;

	/**
	 * The value for the source_file_date field.
	 * @var        string
	 */
	protected $source_file_date;

	/**
	 * The value for the highquality_md5sum field.
	 * @var        string
	 */
	protected $highquality_md5sum;

	/**
	 * The value for the lowquality_md5sum field.
	 * @var        string
	 */
	protected $lowquality_md5sum;

	/**
	 * The value for the has_thumbnail field.
	 * @var        boolean
	 */
	protected $has_thumbnail;

	/**
	 * The value for the thumbnail_width field.
	 * @var        int
	 */
	protected $thumbnail_width;

	/**
	 * The value for the thumbnail_height field.
	 * @var        int
	 */
	protected $thumbnail_height;

	/**
	 * The value for the thumbnail_size field.
	 * @var        int
	 */
	protected $thumbnail_size;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Archive
	 */
	protected $aArchive;

	/**
	 * @var        Category
	 */
	protected $aCategory;

	/**
	 * @var        sfGuardUserProfile
	 */
	protected $asfGuardUserProfile;

	/**
	 * @var        VideoAsset one-to-one related VideoAsset object
	 */
	protected $singleVideoAsset;

	/**
	 * @var        PictureAsset one-to-one related PictureAsset object
	 */
	protected $singlePictureAsset;

	/**
	 * @var        PhotoalbumAsset one-to-one related PhotoalbumAsset object
	 */
	protected $singlePhotoalbumAsset;

	/**
	 * @var        AudioAsset one-to-one related AudioAsset object
	 */
	protected $singleAudioAsset;

	/**
	 * @var        array AccessLogEvent[] Collection to store aggregation of AccessLogEvent objects.
	 */
	protected $collAccessLogEvents;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAccessLogEvents.
	 */
	private $lastAccessLogEventCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'AssetPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [slug] column value.
	 * 
	 * @return     string
	 */
	public function getSlug()
	{
		return $this->slug;
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     int
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get the [archive_id] column value.
	 * 
	 * @return     int
	 */
	public function getArchiveId()
	{
		return $this->archive_id;
	}

	/**
	 * Get the [asset_type] column value.
	 * 
	 * @return     int
	 */
	public function getAssetType()
	{
		return $this->asset_type;
	}

	/**
	 * Get the [assigned_title] column value.
	 * 
	 * @return     string
	 */
	public function getAssignedTitle()
	{
		return $this->assigned_title;
	}

	/**
	 * Get the [category_id] column value.
	 * 
	 * @return     int
	 */
	public function getCategoryId()
	{
		return $this->category_id;
	}

	/**
	 * Get the [notes] column value.
	 * 
	 * @return     string
	 */
	public function getNotes()
	{
		return $this->notes;
	}

	/**
	 * Get the [optionally formatted] temporal [event_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getEventDate($format = 'Y-m-d')
	{
		if ($this->event_date === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->event_date);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->event_date, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [source_filename] column value.
	 * 
	 * @return     string
	 */
	public function getSourceFilename()
	{
		return $this->source_filename;
	}

	/**
	 * Get the [optionally formatted] temporal [source_file_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getSourceFileDate($format = 'Y-m-d')
	{
		if ($this->source_file_date === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->source_file_date);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->source_file_date, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [highquality_md5sum] column value.
	 * 
	 * @return     string
	 */
	public function getHighqualityMd5sum()
	{
		return $this->highquality_md5sum;
	}

	/**
	 * Get the [lowquality_md5sum] column value.
	 * 
	 * @return     string
	 */
	public function getLowqualityMd5sum()
	{
		return $this->lowquality_md5sum;
	}

	/**
	 * Get the [has_thumbnail] column value.
	 * 
	 * @return     boolean
	 */
	public function getHasThumbnail()
	{
		return $this->has_thumbnail;
	}

	/**
	 * Get the [thumbnail_width] column value.
	 * 
	 * @return     int
	 */
	public function getThumbnailWidth()
	{
		return $this->thumbnail_width;
	}

	/**
	 * Get the [thumbnail_height] column value.
	 * 
	 * @return     int
	 */
	public function getThumbnailHeight()
	{
		return $this->thumbnail_height;
	}

	/**
	 * Get the [thumbnail_size] column value.
	 * 
	 * @return     int
	 */
	public function getThumbnailSize()
	{
		return $this->thumbnail_size;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AssetPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [slug] column.
	 * 
	 * @param      string $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setSlug($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->slug !== $v) {
			$this->slug = $v;
			$this->modifiedColumns[] = AssetPeer::SLUG;
		}

		return $this;
	} // setSlug()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      int $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->status !== $v) {
			$this->status = $v;
			$this->modifiedColumns[] = AssetPeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Set the value of [archive_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setArchiveId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->archive_id !== $v) {
			$this->archive_id = $v;
			$this->modifiedColumns[] = AssetPeer::ARCHIVE_ID;
		}

		if ($this->aArchive !== null && $this->aArchive->getId() !== $v) {
			$this->aArchive = null;
		}

		return $this;
	} // setArchiveId()

	/**
	 * Set the value of [asset_type] column.
	 * 
	 * @param      int $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setAssetType($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->asset_type !== $v) {
			$this->asset_type = $v;
			$this->modifiedColumns[] = AssetPeer::ASSET_TYPE;
		}

		return $this;
	} // setAssetType()

	/**
	 * Set the value of [assigned_title] column.
	 * 
	 * @param      string $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setAssignedTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->assigned_title !== $v) {
			$this->assigned_title = $v;
			$this->modifiedColumns[] = AssetPeer::ASSIGNED_TITLE;
		}

		return $this;
	} // setAssignedTitle()

	/**
	 * Set the value of [category_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setCategoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->category_id !== $v) {
			$this->category_id = $v;
			$this->modifiedColumns[] = AssetPeer::CATEGORY_ID;
		}

		if ($this->aCategory !== null && $this->aCategory->getId() !== $v) {
			$this->aCategory = null;
		}

		return $this;
	} // setCategoryId()

	/**
	 * Set the value of [notes] column.
	 * 
	 * @param      string $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setNotes($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->notes !== $v) {
			$this->notes = $v;
			$this->modifiedColumns[] = AssetPeer::NOTES;
		}

		return $this;
	} // setNotes()

	/**
	 * Sets the value of [event_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setEventDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->event_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->event_date !== null && $tmpDt = new DateTime($this->event_date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->event_date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = AssetPeer::EVENT_DATE;
			}
		} // if either are not null

		return $this;
	} // setEventDate()

	/**
	 * Set the value of [source_filename] column.
	 * 
	 * @param      string $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setSourceFilename($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->source_filename !== $v) {
			$this->source_filename = $v;
			$this->modifiedColumns[] = AssetPeer::SOURCE_FILENAME;
		}

		return $this;
	} // setSourceFilename()

	/**
	 * Sets the value of [source_file_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setSourceFileDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->source_file_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->source_file_date !== null && $tmpDt = new DateTime($this->source_file_date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->source_file_date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = AssetPeer::SOURCE_FILE_DATE;
			}
		} // if either are not null

		return $this;
	} // setSourceFileDate()

	/**
	 * Set the value of [highquality_md5sum] column.
	 * 
	 * @param      string $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setHighqualityMd5sum($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->highquality_md5sum !== $v) {
			$this->highquality_md5sum = $v;
			$this->modifiedColumns[] = AssetPeer::HIGHQUALITY_MD5SUM;
		}

		return $this;
	} // setHighqualityMd5sum()

	/**
	 * Set the value of [lowquality_md5sum] column.
	 * 
	 * @param      string $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setLowqualityMd5sum($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->lowquality_md5sum !== $v) {
			$this->lowquality_md5sum = $v;
			$this->modifiedColumns[] = AssetPeer::LOWQUALITY_MD5SUM;
		}

		return $this;
	} // setLowqualityMd5sum()

	/**
	 * Set the value of [has_thumbnail] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setHasThumbnail($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->has_thumbnail !== $v) {
			$this->has_thumbnail = $v;
			$this->modifiedColumns[] = AssetPeer::HAS_THUMBNAIL;
		}

		return $this;
	} // setHasThumbnail()

	/**
	 * Set the value of [thumbnail_width] column.
	 * 
	 * @param      int $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setThumbnailWidth($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->thumbnail_width !== $v) {
			$this->thumbnail_width = $v;
			$this->modifiedColumns[] = AssetPeer::THUMBNAIL_WIDTH;
		}

		return $this;
	} // setThumbnailWidth()

	/**
	 * Set the value of [thumbnail_height] column.
	 * 
	 * @param      int $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setThumbnailHeight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->thumbnail_height !== $v) {
			$this->thumbnail_height = $v;
			$this->modifiedColumns[] = AssetPeer::THUMBNAIL_HEIGHT;
		}

		return $this;
	} // setThumbnailHeight()

	/**
	 * Set the value of [thumbnail_size] column.
	 * 
	 * @param      int $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setThumbnailSize($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->thumbnail_size !== $v) {
			$this->thumbnail_size = $v;
			$this->modifiedColumns[] = AssetPeer::THUMBNAIL_SIZE;
		}

		return $this;
	} // setThumbnailSize()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = AssetPeer::USER_ID;
		}

		if ($this->asfGuardUserProfile !== null && $this->asfGuardUserProfile->getUserId() !== $v) {
			$this->asfGuardUserProfile = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = AssetPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Asset The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = AssetPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->slug = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->status = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->archive_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->asset_type = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->assigned_title = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->category_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->notes = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->event_date = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->source_filename = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->source_file_date = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->highquality_md5sum = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->lowquality_md5sum = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->has_thumbnail = ($row[$startcol + 13] !== null) ? (boolean) $row[$startcol + 13] : null;
			$this->thumbnail_width = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->thumbnail_height = ($row[$startcol + 15] !== null) ? (int) $row[$startcol + 15] : null;
			$this->thumbnail_size = ($row[$startcol + 16] !== null) ? (int) $row[$startcol + 16] : null;
			$this->user_id = ($row[$startcol + 17] !== null) ? (int) $row[$startcol + 17] : null;
			$this->created_at = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->updated_at = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 20; // 20 = AssetPeer::NUM_COLUMNS - AssetPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Asset object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aArchive !== null && $this->archive_id !== $this->aArchive->getId()) {
			$this->aArchive = null;
		}
		if ($this->aCategory !== null && $this->category_id !== $this->aCategory->getId()) {
			$this->aCategory = null;
		}
		if ($this->asfGuardUserProfile !== null && $this->user_id !== $this->asfGuardUserProfile->getUserId()) {
			$this->asfGuardUserProfile = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AssetPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aArchive = null;
			$this->aCategory = null;
			$this->asfGuardUserProfile = null;
			$this->singleVideoAsset = null;

			$this->singlePictureAsset = null;

			$this->singlePhotoalbumAsset = null;

			$this->singleAudioAsset = null;

			$this->collAccessLogEvents = null;
			$this->lastAccessLogEventCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAsset:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				AssetPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAsset:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAsset:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(AssetPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(AssetPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAsset:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				$con->commit();
				AssetPeer::addInstanceToPool($this);
				return $affectedRows;
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aArchive !== null) {
				if ($this->aArchive->isModified() || $this->aArchive->isNew()) {
					$affectedRows += $this->aArchive->save($con);
				}
				$this->setArchive($this->aArchive);
			}

			if ($this->aCategory !== null) {
				if ($this->aCategory->isModified() || $this->aCategory->isNew()) {
					$affectedRows += $this->aCategory->save($con);
				}
				$this->setCategory($this->aCategory);
			}

			if ($this->asfGuardUserProfile !== null) {
				if ($this->asfGuardUserProfile->isModified() || $this->asfGuardUserProfile->isNew()) {
					$affectedRows += $this->asfGuardUserProfile->save($con);
				}
				$this->setsfGuardUserProfile($this->asfGuardUserProfile);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AssetPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AssetPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AssetPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->singleVideoAsset !== null) {
				if (!$this->singleVideoAsset->isDeleted()) {
						$affectedRows += $this->singleVideoAsset->save($con);
				}
			}

			if ($this->singlePictureAsset !== null) {
				if (!$this->singlePictureAsset->isDeleted()) {
						$affectedRows += $this->singlePictureAsset->save($con);
				}
			}

			if ($this->singlePhotoalbumAsset !== null) {
				if (!$this->singlePhotoalbumAsset->isDeleted()) {
						$affectedRows += $this->singlePhotoalbumAsset->save($con);
				}
			}

			if ($this->singleAudioAsset !== null) {
				if (!$this->singleAudioAsset->isDeleted()) {
						$affectedRows += $this->singleAudioAsset->save($con);
				}
			}

			if ($this->collAccessLogEvents !== null) {
				foreach ($this->collAccessLogEvents as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aArchive !== null) {
				if (!$this->aArchive->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aArchive->getValidationFailures());
				}
			}

			if ($this->aCategory !== null) {
				if (!$this->aCategory->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCategory->getValidationFailures());
				}
			}

			if ($this->asfGuardUserProfile !== null) {
				if (!$this->asfGuardUserProfile->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserProfile->getValidationFailures());
				}
			}


			if (($retval = AssetPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->singleVideoAsset !== null) {
					if (!$this->singleVideoAsset->validate($columns)) {
						$failureMap = array_merge($failureMap, $this->singleVideoAsset->getValidationFailures());
					}
				}

				if ($this->singlePictureAsset !== null) {
					if (!$this->singlePictureAsset->validate($columns)) {
						$failureMap = array_merge($failureMap, $this->singlePictureAsset->getValidationFailures());
					}
				}

				if ($this->singlePhotoalbumAsset !== null) {
					if (!$this->singlePhotoalbumAsset->validate($columns)) {
						$failureMap = array_merge($failureMap, $this->singlePhotoalbumAsset->getValidationFailures());
					}
				}

				if ($this->singleAudioAsset !== null) {
					if (!$this->singleAudioAsset->validate($columns)) {
						$failureMap = array_merge($failureMap, $this->singleAudioAsset->getValidationFailures());
					}
				}

				if ($this->collAccessLogEvents !== null) {
					foreach ($this->collAccessLogEvents as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AssetPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getSlug();
				break;
			case 2:
				return $this->getStatus();
				break;
			case 3:
				return $this->getArchiveId();
				break;
			case 4:
				return $this->getAssetType();
				break;
			case 5:
				return $this->getAssignedTitle();
				break;
			case 6:
				return $this->getCategoryId();
				break;
			case 7:
				return $this->getNotes();
				break;
			case 8:
				return $this->getEventDate();
				break;
			case 9:
				return $this->getSourceFilename();
				break;
			case 10:
				return $this->getSourceFileDate();
				break;
			case 11:
				return $this->getHighqualityMd5sum();
				break;
			case 12:
				return $this->getLowqualityMd5sum();
				break;
			case 13:
				return $this->getHasThumbnail();
				break;
			case 14:
				return $this->getThumbnailWidth();
				break;
			case 15:
				return $this->getThumbnailHeight();
				break;
			case 16:
				return $this->getThumbnailSize();
				break;
			case 17:
				return $this->getUserId();
				break;
			case 18:
				return $this->getCreatedAt();
				break;
			case 19:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AssetPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getSlug(),
			$keys[2] => $this->getStatus(),
			$keys[3] => $this->getArchiveId(),
			$keys[4] => $this->getAssetType(),
			$keys[5] => $this->getAssignedTitle(),
			$keys[6] => $this->getCategoryId(),
			$keys[7] => $this->getNotes(),
			$keys[8] => $this->getEventDate(),
			$keys[9] => $this->getSourceFilename(),
			$keys[10] => $this->getSourceFileDate(),
			$keys[11] => $this->getHighqualityMd5sum(),
			$keys[12] => $this->getLowqualityMd5sum(),
			$keys[13] => $this->getHasThumbnail(),
			$keys[14] => $this->getThumbnailWidth(),
			$keys[15] => $this->getThumbnailHeight(),
			$keys[16] => $this->getThumbnailSize(),
			$keys[17] => $this->getUserId(),
			$keys[18] => $this->getCreatedAt(),
			$keys[19] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AssetPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setSlug($value);
				break;
			case 2:
				$this->setStatus($value);
				break;
			case 3:
				$this->setArchiveId($value);
				break;
			case 4:
				$this->setAssetType($value);
				break;
			case 5:
				$this->setAssignedTitle($value);
				break;
			case 6:
				$this->setCategoryId($value);
				break;
			case 7:
				$this->setNotes($value);
				break;
			case 8:
				$this->setEventDate($value);
				break;
			case 9:
				$this->setSourceFilename($value);
				break;
			case 10:
				$this->setSourceFileDate($value);
				break;
			case 11:
				$this->setHighqualityMd5sum($value);
				break;
			case 12:
				$this->setLowqualityMd5sum($value);
				break;
			case 13:
				$this->setHasThumbnail($value);
				break;
			case 14:
				$this->setThumbnailWidth($value);
				break;
			case 15:
				$this->setThumbnailHeight($value);
				break;
			case 16:
				$this->setThumbnailSize($value);
				break;
			case 17:
				$this->setUserId($value);
				break;
			case 18:
				$this->setCreatedAt($value);
				break;
			case 19:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AssetPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setSlug($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setStatus($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setArchiveId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setAssetType($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setAssignedTitle($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCategoryId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setNotes($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setEventDate($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setSourceFilename($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setSourceFileDate($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setHighqualityMd5sum($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setLowqualityMd5sum($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setHasThumbnail($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setThumbnailWidth($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setThumbnailHeight($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setThumbnailSize($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setUserId($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setCreatedAt($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setUpdatedAt($arr[$keys[19]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AssetPeer::DATABASE_NAME);

		if ($this->isColumnModified(AssetPeer::ID)) $criteria->add(AssetPeer::ID, $this->id);
		if ($this->isColumnModified(AssetPeer::SLUG)) $criteria->add(AssetPeer::SLUG, $this->slug);
		if ($this->isColumnModified(AssetPeer::STATUS)) $criteria->add(AssetPeer::STATUS, $this->status);
		if ($this->isColumnModified(AssetPeer::ARCHIVE_ID)) $criteria->add(AssetPeer::ARCHIVE_ID, $this->archive_id);
		if ($this->isColumnModified(AssetPeer::ASSET_TYPE)) $criteria->add(AssetPeer::ASSET_TYPE, $this->asset_type);
		if ($this->isColumnModified(AssetPeer::ASSIGNED_TITLE)) $criteria->add(AssetPeer::ASSIGNED_TITLE, $this->assigned_title);
		if ($this->isColumnModified(AssetPeer::CATEGORY_ID)) $criteria->add(AssetPeer::CATEGORY_ID, $this->category_id);
		if ($this->isColumnModified(AssetPeer::NOTES)) $criteria->add(AssetPeer::NOTES, $this->notes);
		if ($this->isColumnModified(AssetPeer::EVENT_DATE)) $criteria->add(AssetPeer::EVENT_DATE, $this->event_date);
		if ($this->isColumnModified(AssetPeer::SOURCE_FILENAME)) $criteria->add(AssetPeer::SOURCE_FILENAME, $this->source_filename);
		if ($this->isColumnModified(AssetPeer::SOURCE_FILE_DATE)) $criteria->add(AssetPeer::SOURCE_FILE_DATE, $this->source_file_date);
		if ($this->isColumnModified(AssetPeer::HIGHQUALITY_MD5SUM)) $criteria->add(AssetPeer::HIGHQUALITY_MD5SUM, $this->highquality_md5sum);
		if ($this->isColumnModified(AssetPeer::LOWQUALITY_MD5SUM)) $criteria->add(AssetPeer::LOWQUALITY_MD5SUM, $this->lowquality_md5sum);
		if ($this->isColumnModified(AssetPeer::HAS_THUMBNAIL)) $criteria->add(AssetPeer::HAS_THUMBNAIL, $this->has_thumbnail);
		if ($this->isColumnModified(AssetPeer::THUMBNAIL_WIDTH)) $criteria->add(AssetPeer::THUMBNAIL_WIDTH, $this->thumbnail_width);
		if ($this->isColumnModified(AssetPeer::THUMBNAIL_HEIGHT)) $criteria->add(AssetPeer::THUMBNAIL_HEIGHT, $this->thumbnail_height);
		if ($this->isColumnModified(AssetPeer::THUMBNAIL_SIZE)) $criteria->add(AssetPeer::THUMBNAIL_SIZE, $this->thumbnail_size);
		if ($this->isColumnModified(AssetPeer::USER_ID)) $criteria->add(AssetPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(AssetPeer::CREATED_AT)) $criteria->add(AssetPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(AssetPeer::UPDATED_AT)) $criteria->add(AssetPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AssetPeer::DATABASE_NAME);

		$criteria->add(AssetPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Asset (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setSlug($this->slug);

		$copyObj->setStatus($this->status);

		$copyObj->setArchiveId($this->archive_id);

		$copyObj->setAssetType($this->asset_type);

		$copyObj->setAssignedTitle($this->assigned_title);

		$copyObj->setCategoryId($this->category_id);

		$copyObj->setNotes($this->notes);

		$copyObj->setEventDate($this->event_date);

		$copyObj->setSourceFilename($this->source_filename);

		$copyObj->setSourceFileDate($this->source_file_date);

		$copyObj->setHighqualityMd5sum($this->highquality_md5sum);

		$copyObj->setLowqualityMd5sum($this->lowquality_md5sum);

		$copyObj->setHasThumbnail($this->has_thumbnail);

		$copyObj->setThumbnailWidth($this->thumbnail_width);

		$copyObj->setThumbnailHeight($this->thumbnail_height);

		$copyObj->setThumbnailSize($this->thumbnail_size);

		$copyObj->setUserId($this->user_id);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			$relObj = $this->getVideoAsset();
			if ($relObj) {
				$copyObj->setVideoAsset($relObj->copy($deepCopy));
			}

			$relObj = $this->getPictureAsset();
			if ($relObj) {
				$copyObj->setPictureAsset($relObj->copy($deepCopy));
			}

			$relObj = $this->getPhotoalbumAsset();
			if ($relObj) {
				$copyObj->setPhotoalbumAsset($relObj->copy($deepCopy));
			}

			$relObj = $this->getAudioAsset();
			if ($relObj) {
				$copyObj->setAudioAsset($relObj->copy($deepCopy));
			}

			foreach ($this->getAccessLogEvents() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAccessLogEvent($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Asset Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AssetPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AssetPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Archive object.
	 *
	 * @param      Archive $v
	 * @return     Asset The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setArchive(Archive $v = null)
	{
		if ($v === null) {
			$this->setArchiveId(NULL);
		} else {
			$this->setArchiveId($v->getId());
		}

		$this->aArchive = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Archive object, it will not be re-added.
		if ($v !== null) {
			$v->addAsset($this);
		}

		return $this;
	}


	/**
	 * Get the associated Archive object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Archive The associated Archive object.
	 * @throws     PropelException
	 */
	public function getArchive(PropelPDO $con = null)
	{
		if ($this->aArchive === null && ($this->archive_id !== null)) {
			$this->aArchive = ArchivePeer::retrieveByPk($this->archive_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aArchive->addAssets($this);
			 */
		}
		return $this->aArchive;
	}

	/**
	 * Declares an association between this object and a Category object.
	 *
	 * @param      Category $v
	 * @return     Asset The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCategory(Category $v = null)
	{
		if ($v === null) {
			$this->setCategoryId(NULL);
		} else {
			$this->setCategoryId($v->getId());
		}

		$this->aCategory = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Category object, it will not be re-added.
		if ($v !== null) {
			$v->addAsset($this);
		}

		return $this;
	}


	/**
	 * Get the associated Category object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Category The associated Category object.
	 * @throws     PropelException
	 */
	public function getCategory(PropelPDO $con = null)
	{
		if ($this->aCategory === null && ($this->category_id !== null)) {
			$this->aCategory = CategoryPeer::retrieveByPk($this->category_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCategory->addAssets($this);
			 */
		}
		return $this->aCategory;
	}

	/**
	 * Declares an association between this object and a sfGuardUserProfile object.
	 *
	 * @param      sfGuardUserProfile $v
	 * @return     Asset The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserProfile(sfGuardUserProfile $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getUserId());
		}

		$this->asfGuardUserProfile = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUserProfile object, it will not be re-added.
		if ($v !== null) {
			$v->addAsset($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUserProfile object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUserProfile The associated sfGuardUserProfile object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserProfile(PropelPDO $con = null)
	{
		if ($this->asfGuardUserProfile === null && ($this->user_id !== null)) {
			$this->asfGuardUserProfile = sfGuardUserProfilePeer::retrieveByPk($this->user_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserProfile->addAssets($this);
			 */
		}
		return $this->asfGuardUserProfile;
	}

	/**
	 * Gets a single VideoAsset object, which is related to this object by a one-to-one relationship.
	 *
	 * @param      PropelPDO $con
	 * @return     VideoAsset
	 * @throws     PropelException
	 */
	public function getVideoAsset(PropelPDO $con = null)
	{

		if ($this->singleVideoAsset === null && !$this->isNew()) {
			$this->singleVideoAsset = VideoAssetPeer::retrieveByPK($this->id, $con);
		}

		return $this->singleVideoAsset;
	}

	/**
	 * Sets a single VideoAsset object as related to this object by a one-to-one relationship.
	 *
	 * @param      VideoAsset $l VideoAsset
	 * @return     Asset The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setVideoAsset(VideoAsset $v)
	{
		$this->singleVideoAsset = $v;

		// Make sure that that the passed-in VideoAsset isn't already associated with this object
		if ($v->getAsset() === null) {
			$v->setAsset($this);
		}

		return $this;
	}

	/**
	 * Gets a single PictureAsset object, which is related to this object by a one-to-one relationship.
	 *
	 * @param      PropelPDO $con
	 * @return     PictureAsset
	 * @throws     PropelException
	 */
	public function getPictureAsset(PropelPDO $con = null)
	{

		if ($this->singlePictureAsset === null && !$this->isNew()) {
			$this->singlePictureAsset = PictureAssetPeer::retrieveByPK($this->id, $con);
		}

		return $this->singlePictureAsset;
	}

	/**
	 * Sets a single PictureAsset object as related to this object by a one-to-one relationship.
	 *
	 * @param      PictureAsset $l PictureAsset
	 * @return     Asset The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPictureAsset(PictureAsset $v)
	{
		$this->singlePictureAsset = $v;

		// Make sure that that the passed-in PictureAsset isn't already associated with this object
		if ($v->getAsset() === null) {
			$v->setAsset($this);
		}

		return $this;
	}

	/**
	 * Gets a single PhotoalbumAsset object, which is related to this object by a one-to-one relationship.
	 *
	 * @param      PropelPDO $con
	 * @return     PhotoalbumAsset
	 * @throws     PropelException
	 */
	public function getPhotoalbumAsset(PropelPDO $con = null)
	{

		if ($this->singlePhotoalbumAsset === null && !$this->isNew()) {
			$this->singlePhotoalbumAsset = PhotoalbumAssetPeer::retrieveByPK($this->id, $con);
		}

		return $this->singlePhotoalbumAsset;
	}

	/**
	 * Sets a single PhotoalbumAsset object as related to this object by a one-to-one relationship.
	 *
	 * @param      PhotoalbumAsset $l PhotoalbumAsset
	 * @return     Asset The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPhotoalbumAsset(PhotoalbumAsset $v)
	{
		$this->singlePhotoalbumAsset = $v;

		// Make sure that that the passed-in PhotoalbumAsset isn't already associated with this object
		if ($v->getAsset() === null) {
			$v->setAsset($this);
		}

		return $this;
	}

	/**
	 * Gets a single AudioAsset object, which is related to this object by a one-to-one relationship.
	 *
	 * @param      PropelPDO $con
	 * @return     AudioAsset
	 * @throws     PropelException
	 */
	public function getAudioAsset(PropelPDO $con = null)
	{

		if ($this->singleAudioAsset === null && !$this->isNew()) {
			$this->singleAudioAsset = AudioAssetPeer::retrieveByPK($this->id, $con);
		}

		return $this->singleAudioAsset;
	}

	/**
	 * Sets a single AudioAsset object as related to this object by a one-to-one relationship.
	 *
	 * @param      AudioAsset $l AudioAsset
	 * @return     Asset The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAudioAsset(AudioAsset $v)
	{
		$this->singleAudioAsset = $v;

		// Make sure that that the passed-in AudioAsset isn't already associated with this object
		if ($v->getAsset() === null) {
			$v->setAsset($this);
		}

		return $this;
	}

	/**
	 * Clears out the collAccessLogEvents collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAccessLogEvents()
	 */
	public function clearAccessLogEvents()
	{
		$this->collAccessLogEvents = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAccessLogEvents collection (array).
	 *
	 * By default this just sets the collAccessLogEvents collection to an empty array (like clearcollAccessLogEvents());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAccessLogEvents()
	{
		$this->collAccessLogEvents = array();
	}

	/**
	 * Gets an array of AccessLogEvent objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Asset has previously been saved, it will retrieve
	 * related AccessLogEvents from storage. If this Asset is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AccessLogEvent[]
	 * @throws     PropelException
	 */
	public function getAccessLogEvents($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AssetPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAccessLogEvents === null) {
			if ($this->isNew()) {
			   $this->collAccessLogEvents = array();
			} else {

				$criteria->add(AccessLogEventPeer::ASSET_ID, $this->id);

				AccessLogEventPeer::addSelectColumns($criteria);
				$this->collAccessLogEvents = AccessLogEventPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AccessLogEventPeer::ASSET_ID, $this->id);

				AccessLogEventPeer::addSelectColumns($criteria);
				if (!isset($this->lastAccessLogEventCriteria) || !$this->lastAccessLogEventCriteria->equals($criteria)) {
					$this->collAccessLogEvents = AccessLogEventPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAccessLogEventCriteria = $criteria;
		return $this->collAccessLogEvents;
	}

	/**
	 * Returns the number of related AccessLogEvent objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AccessLogEvent objects.
	 * @throws     PropelException
	 */
	public function countAccessLogEvents(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AssetPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAccessLogEvents === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AccessLogEventPeer::ASSET_ID, $this->id);

				$count = AccessLogEventPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AccessLogEventPeer::ASSET_ID, $this->id);

				if (!isset($this->lastAccessLogEventCriteria) || !$this->lastAccessLogEventCriteria->equals($criteria)) {
					$count = AccessLogEventPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAccessLogEvents);
				}
			} else {
				$count = count($this->collAccessLogEvents);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AccessLogEvent object to this object
	 * through the AccessLogEvent foreign key attribute.
	 *
	 * @param      AccessLogEvent $l AccessLogEvent
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAccessLogEvent(AccessLogEvent $l)
	{
		if ($this->collAccessLogEvents === null) {
			$this->initAccessLogEvents();
		}
		if (!in_array($l, $this->collAccessLogEvents, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAccessLogEvents, $l);
			$l->setAsset($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Asset is new, it will return
	 * an empty collection; or if this Asset has previously
	 * been saved, it will retrieve related AccessLogEvents from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Asset.
	 */
	public function getAccessLogEventsJoinsfGuardUserProfile($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AssetPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAccessLogEvents === null) {
			if ($this->isNew()) {
				$this->collAccessLogEvents = array();
			} else {

				$criteria->add(AccessLogEventPeer::ASSET_ID, $this->id);

				$this->collAccessLogEvents = AccessLogEventPeer::doSelectJoinsfGuardUserProfile($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AccessLogEventPeer::ASSET_ID, $this->id);

			if (!isset($this->lastAccessLogEventCriteria) || !$this->lastAccessLogEventCriteria->equals($criteria)) {
				$this->collAccessLogEvents = AccessLogEventPeer::doSelectJoinsfGuardUserProfile($criteria, $con, $join_behavior);
			}
		}
		$this->lastAccessLogEventCriteria = $criteria;

		return $this->collAccessLogEvents;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->singleVideoAsset) {
				$this->singleVideoAsset->clearAllReferences($deep);
			}
			if ($this->singlePictureAsset) {
				$this->singlePictureAsset->clearAllReferences($deep);
			}
			if ($this->singlePhotoalbumAsset) {
				$this->singlePhotoalbumAsset->clearAllReferences($deep);
			}
			if ($this->singleAudioAsset) {
				$this->singleAudioAsset->clearAllReferences($deep);
			}
			if ($this->collAccessLogEvents) {
				foreach ((array) $this->collAccessLogEvents as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->singleVideoAsset = null;
		$this->singlePictureAsset = null;
		$this->singlePhotoalbumAsset = null;
		$this->singleAudioAsset = null;
		$this->collAccessLogEvents = null;
			$this->aArchive = null;
			$this->aCategory = null;
			$this->asfGuardUserProfile = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseAsset:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseAsset::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseAsset
