<?php


/**
 * This class defines the structure of the 'asset' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Feb  3 22:29:50 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AssetTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AssetTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('asset');
		$this->setPhpName('Asset');
		$this->setClassname('Asset');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('asset_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('SLUG', 'Slug', 'VARCHAR', true, 50, null);
		$this->addForeignKey('ASSET_TYPE_ID', 'AssetTypeId', 'INTEGER', 'asset_type', 'ID', false, null, null);
		$this->addColumn('ORIGINAL_NAME', 'OriginalName', 'VARCHAR', false, 255, null);
		$this->addColumn('ASSIGNED_TITLE', 'AssignedTitle', 'VARCHAR', false, 255, null);
		$this->addColumn('MD5SUM', 'Md5sum', 'VARCHAR', false, 32, null);
		$this->addColumn('NOTES', 'Notes', 'LONGVARCHAR', false, null, null);
		$this->addColumn('FILE_DATE', 'FileDate', 'DATE', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('AssetType', 'AssetType', RelationMap::MANY_TO_ONE, array('asset_type_id' => 'id', ), null, null);
    $this->addRelation('AccessLog', 'AccessLog', RelationMap::ONE_TO_MANY, array('id' => 'asset_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // AssetTableMap
