generator:
  class: sfPropelGenerator
  param:
    model_class:           Archive
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Archive
    plural:                Archives
    route_prefix:          archive
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ id, slug, created_at, burned_at ]
        object_actions:
          _edit:           ~
          mark_as_burned:  ~
          get_info:        ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
