<?php

require 'lib/model/om/BaseAccessLogEvent.php';


/**
 * Skeleton subclass for representing a row from the 'access_log_event' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Feb 27 09:27:33 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AccessLogEvent extends BaseAccessLogEvent {

} // AccessLogEvent
