<?php

require 'lib/model/om/BasePhotoalbumAsset.php';


/**
 * Skeleton subclass for representing a row from the 'photoalbum_asset' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Feb  8 22:36:15 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PhotoalbumAsset extends BasePhotoalbumAsset {

	protected
		$_uniqid,
		$_assetFile;

	public function getPhotoalbumFile($session='')
	{
    // returns the low quality file
    if (!$this->_assetFile)
    {
      $this->_uniqid=$this->getAsset()->getUniqid();
      $this->_assetFile=new PhotoalbumFile($this->_uniqid, $session);
    }
		return $this->_assetFile;
	}
  
  public function gatherInfo()
  {
    $this->setPicturesCount($this->getPhotoalbumFile()->getPicturesCount());
    return $this;
  }
  
  public function getPictureWidth($number, $session='')
  {
    // simple proxy
    return $this->getPhotoalbumFile($session)->getPictureWidth($number);
  }
  
  public function getReducedPictureWidth($number, $session='')
  {
    return round($this->getPictureWidth($number, $session)/wvConfig::get('thumbnail_photoalbum_reduction', 4));
  }
  
  public function getPictureHeight($number, $session='')
  {
    // simple proxy
    return $this->getPhotoalbumFile($session)->getPictureHeight($number);
  }
  
  public function getReducedPictureHeight($number, $session='')
  {
    return round($this->getPictureHeight($number, $session)/wvConfig::get('thumbnail_photoalbum_reduction', 4));
  }

  public function getFilename($number, $session='')
  {
    // simple proxy
    return $this->getPhotoalbumFile($session)->getFilename($number);
  }

} // PhotoalbumAsset
