<?php

require 'lib/model/om/BasePicture.php';


/**
 * Skeleton subclass for representing a row from the 'picture' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Jan  8 17:21:37 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Picture extends BasePicture {

	public function __toString()
	{
		return 'picture_' . $this->getId();
	}
	
	public function getSortedDescriptions()
	{
		$c = new Criteria();
		$c->addAscendingOrderByColumn(DescriptionPeer::ID);
		return parent::getDescriptions($c);
	}
	

} // Picture
