<?php

/**
 * Base static class for performing query and update operations on the 'asset' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Feb  6 20:09:41 2010
 *
 * @package    lib.model.om
 */
abstract class BaseAssetPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'asset';

	/** the related Propel class for this table */
	const OM_CLASS = 'Asset';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Asset';

	/** the related TableMap class for this table */
	const TM_CLASS = 'AssetTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 25;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'asset.ID';

	/** the column name for the SLUG field */
	const SLUG = 'asset.SLUG';

	/** the column name for the ASSET_TYPE_ID field */
	const ASSET_TYPE_ID = 'asset.ASSET_TYPE_ID';

	/** the column name for the ASSIGNED_TITLE field */
	const ASSIGNED_TITLE = 'asset.ASSIGNED_TITLE';

	/** the column name for the CATEGORY_ID field */
	const CATEGORY_ID = 'asset.CATEGORY_ID';

	/** the column name for the NOTES field */
	const NOTES = 'asset.NOTES';

	/** the column name for the DURATION field */
	const DURATION = 'asset.DURATION';

	/** the column name for the SOURCE_FILENAME field */
	const SOURCE_FILENAME = 'asset.SOURCE_FILENAME';

	/** the column name for the SOURCE_FILE_DATE field */
	const SOURCE_FILE_DATE = 'asset.SOURCE_FILE_DATE';

	/** the column name for the HIGHQUALITY_WIDTH field */
	const HIGHQUALITY_WIDTH = 'asset.HIGHQUALITY_WIDTH';

	/** the column name for the HIGHQUALITY_HEIGHT field */
	const HIGHQUALITY_HEIGHT = 'asset.HIGHQUALITY_HEIGHT';

	/** the column name for the HIGHQUALITY_VIDEO_CODEC field */
	const HIGHQUALITY_VIDEO_CODEC = 'asset.HIGHQUALITY_VIDEO_CODEC';

	/** the column name for the HIGHQUALITY_AUDIO_CODEC field */
	const HIGHQUALITY_AUDIO_CODEC = 'asset.HIGHQUALITY_AUDIO_CODEC';

	/** the column name for the HIGHQUALITY_FRAME_RATE field */
	const HIGHQUALITY_FRAME_RATE = 'asset.HIGHQUALITY_FRAME_RATE';

	/** the column name for the HIGHQUALITY_MD5SUM field */
	const HIGHQUALITY_MD5SUM = 'asset.HIGHQUALITY_MD5SUM';

	/** the column name for the ARCHIVE_ID field */
	const ARCHIVE_ID = 'asset.ARCHIVE_ID';

	/** the column name for the LOWQUALITY_WIDTH field */
	const LOWQUALITY_WIDTH = 'asset.LOWQUALITY_WIDTH';

	/** the column name for the LOWQUALITY_HEIGHT field */
	const LOWQUALITY_HEIGHT = 'asset.LOWQUALITY_HEIGHT';

	/** the column name for the LOWQUALITY_VIDEO_CODEC field */
	const LOWQUALITY_VIDEO_CODEC = 'asset.LOWQUALITY_VIDEO_CODEC';

	/** the column name for the LOWQUALITY_AUDIO_CODEC field */
	const LOWQUALITY_AUDIO_CODEC = 'asset.LOWQUALITY_AUDIO_CODEC';

	/** the column name for the LOWQUALITY_FRAME_RATE field */
	const LOWQUALITY_FRAME_RATE = 'asset.LOWQUALITY_FRAME_RATE';

	/** the column name for the LOWQUALITY_MD5SUM field */
	const LOWQUALITY_MD5SUM = 'asset.LOWQUALITY_MD5SUM';

	/** the column name for the USER_ID field */
	const USER_ID = 'asset.USER_ID';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'asset.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'asset.UPDATED_AT';

	/**
	 * An identiy map to hold any loaded instances of Asset objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Asset[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Slug', 'AssetTypeId', 'AssignedTitle', 'CategoryId', 'Notes', 'Duration', 'SourceFilename', 'SourceFileDate', 'HighqualityWidth', 'HighqualityHeight', 'HighqualityVideoCodec', 'HighqualityAudioCodec', 'HighqualityFrameRate', 'HighqualityMd5sum', 'ArchiveId', 'LowqualityWidth', 'LowqualityHeight', 'LowqualityVideoCodec', 'LowqualityAudioCodec', 'LowqualityFrameRate', 'LowqualityMd5sum', 'UserId', 'CreatedAt', 'UpdatedAt', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'slug', 'assetTypeId', 'assignedTitle', 'categoryId', 'notes', 'duration', 'sourceFilename', 'sourceFileDate', 'highqualityWidth', 'highqualityHeight', 'highqualityVideoCodec', 'highqualityAudioCodec', 'highqualityFrameRate', 'highqualityMd5sum', 'archiveId', 'lowqualityWidth', 'lowqualityHeight', 'lowqualityVideoCodec', 'lowqualityAudioCodec', 'lowqualityFrameRate', 'lowqualityMd5sum', 'userId', 'createdAt', 'updatedAt', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::SLUG, self::ASSET_TYPE_ID, self::ASSIGNED_TITLE, self::CATEGORY_ID, self::NOTES, self::DURATION, self::SOURCE_FILENAME, self::SOURCE_FILE_DATE, self::HIGHQUALITY_WIDTH, self::HIGHQUALITY_HEIGHT, self::HIGHQUALITY_VIDEO_CODEC, self::HIGHQUALITY_AUDIO_CODEC, self::HIGHQUALITY_FRAME_RATE, self::HIGHQUALITY_MD5SUM, self::ARCHIVE_ID, self::LOWQUALITY_WIDTH, self::LOWQUALITY_HEIGHT, self::LOWQUALITY_VIDEO_CODEC, self::LOWQUALITY_AUDIO_CODEC, self::LOWQUALITY_FRAME_RATE, self::LOWQUALITY_MD5SUM, self::USER_ID, self::CREATED_AT, self::UPDATED_AT, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'slug', 'asset_type_id', 'assigned_title', 'category_id', 'notes', 'duration', 'source_filename', 'source_file_date', 'highquality_width', 'highquality_height', 'highquality_video_codec', 'highquality_audio_codec', 'highquality_frame_rate', 'highquality_md5sum', 'archive_id', 'lowquality_width', 'lowquality_height', 'lowquality_video_codec', 'lowquality_audio_codec', 'lowquality_frame_rate', 'lowquality_md5sum', 'user_id', 'created_at', 'updated_at', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Slug' => 1, 'AssetTypeId' => 2, 'AssignedTitle' => 3, 'CategoryId' => 4, 'Notes' => 5, 'Duration' => 6, 'SourceFilename' => 7, 'SourceFileDate' => 8, 'HighqualityWidth' => 9, 'HighqualityHeight' => 10, 'HighqualityVideoCodec' => 11, 'HighqualityAudioCodec' => 12, 'HighqualityFrameRate' => 13, 'HighqualityMd5sum' => 14, 'ArchiveId' => 15, 'LowqualityWidth' => 16, 'LowqualityHeight' => 17, 'LowqualityVideoCodec' => 18, 'LowqualityAudioCodec' => 19, 'LowqualityFrameRate' => 20, 'LowqualityMd5sum' => 21, 'UserId' => 22, 'CreatedAt' => 23, 'UpdatedAt' => 24, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'slug' => 1, 'assetTypeId' => 2, 'assignedTitle' => 3, 'categoryId' => 4, 'notes' => 5, 'duration' => 6, 'sourceFilename' => 7, 'sourceFileDate' => 8, 'highqualityWidth' => 9, 'highqualityHeight' => 10, 'highqualityVideoCodec' => 11, 'highqualityAudioCodec' => 12, 'highqualityFrameRate' => 13, 'highqualityMd5sum' => 14, 'archiveId' => 15, 'lowqualityWidth' => 16, 'lowqualityHeight' => 17, 'lowqualityVideoCodec' => 18, 'lowqualityAudioCodec' => 19, 'lowqualityFrameRate' => 20, 'lowqualityMd5sum' => 21, 'userId' => 22, 'createdAt' => 23, 'updatedAt' => 24, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::SLUG => 1, self::ASSET_TYPE_ID => 2, self::ASSIGNED_TITLE => 3, self::CATEGORY_ID => 4, self::NOTES => 5, self::DURATION => 6, self::SOURCE_FILENAME => 7, self::SOURCE_FILE_DATE => 8, self::HIGHQUALITY_WIDTH => 9, self::HIGHQUALITY_HEIGHT => 10, self::HIGHQUALITY_VIDEO_CODEC => 11, self::HIGHQUALITY_AUDIO_CODEC => 12, self::HIGHQUALITY_FRAME_RATE => 13, self::HIGHQUALITY_MD5SUM => 14, self::ARCHIVE_ID => 15, self::LOWQUALITY_WIDTH => 16, self::LOWQUALITY_HEIGHT => 17, self::LOWQUALITY_VIDEO_CODEC => 18, self::LOWQUALITY_AUDIO_CODEC => 19, self::LOWQUALITY_FRAME_RATE => 20, self::LOWQUALITY_MD5SUM => 21, self::USER_ID => 22, self::CREATED_AT => 23, self::UPDATED_AT => 24, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'slug' => 1, 'asset_type_id' => 2, 'assigned_title' => 3, 'category_id' => 4, 'notes' => 5, 'duration' => 6, 'source_filename' => 7, 'source_file_date' => 8, 'highquality_width' => 9, 'highquality_height' => 10, 'highquality_video_codec' => 11, 'highquality_audio_codec' => 12, 'highquality_frame_rate' => 13, 'highquality_md5sum' => 14, 'archive_id' => 15, 'lowquality_width' => 16, 'lowquality_height' => 17, 'lowquality_video_codec' => 18, 'lowquality_audio_codec' => 19, 'lowquality_frame_rate' => 20, 'lowquality_md5sum' => 21, 'user_id' => 22, 'created_at' => 23, 'updated_at' => 24, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. AssetPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(AssetPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(AssetPeer::ID);
		$criteria->addSelectColumn(AssetPeer::SLUG);
		$criteria->addSelectColumn(AssetPeer::ASSET_TYPE_ID);
		$criteria->addSelectColumn(AssetPeer::ASSIGNED_TITLE);
		$criteria->addSelectColumn(AssetPeer::CATEGORY_ID);
		$criteria->addSelectColumn(AssetPeer::NOTES);
		$criteria->addSelectColumn(AssetPeer::DURATION);
		$criteria->addSelectColumn(AssetPeer::SOURCE_FILENAME);
		$criteria->addSelectColumn(AssetPeer::SOURCE_FILE_DATE);
		$criteria->addSelectColumn(AssetPeer::HIGHQUALITY_WIDTH);
		$criteria->addSelectColumn(AssetPeer::HIGHQUALITY_HEIGHT);
		$criteria->addSelectColumn(AssetPeer::HIGHQUALITY_VIDEO_CODEC);
		$criteria->addSelectColumn(AssetPeer::HIGHQUALITY_AUDIO_CODEC);
		$criteria->addSelectColumn(AssetPeer::HIGHQUALITY_FRAME_RATE);
		$criteria->addSelectColumn(AssetPeer::HIGHQUALITY_MD5SUM);
		$criteria->addSelectColumn(AssetPeer::ARCHIVE_ID);
		$criteria->addSelectColumn(AssetPeer::LOWQUALITY_WIDTH);
		$criteria->addSelectColumn(AssetPeer::LOWQUALITY_HEIGHT);
		$criteria->addSelectColumn(AssetPeer::LOWQUALITY_VIDEO_CODEC);
		$criteria->addSelectColumn(AssetPeer::LOWQUALITY_AUDIO_CODEC);
		$criteria->addSelectColumn(AssetPeer::LOWQUALITY_FRAME_RATE);
		$criteria->addSelectColumn(AssetPeer::LOWQUALITY_MD5SUM);
		$criteria->addSelectColumn(AssetPeer::USER_ID);
		$criteria->addSelectColumn(AssetPeer::CREATED_AT);
		$criteria->addSelectColumn(AssetPeer::UPDATED_AT);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AssetPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AssetPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Asset
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = AssetPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return AssetPeer::populateObjects(AssetPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			AssetPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Asset $value A Asset object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Asset $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Asset object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Asset) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Asset object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Asset Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to asset
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = AssetPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = AssetPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = AssetPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				AssetPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related AssetType table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAssetType(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AssetPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AssetPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(AssetPeer::ASSET_TYPE_ID, AssetTypePeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Category table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinCategory(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AssetPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AssetPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(AssetPeer::CATEGORY_ID, CategoryPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Archive table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinArchive(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AssetPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AssetPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(AssetPeer::ARCHIVE_ID, ArchivePeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related sfGuardUserProfile table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinsfGuardUserProfile(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AssetPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AssetPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(AssetPeer::USER_ID, sfGuardUserProfilePeer::USER_ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Asset objects pre-filled with their AssetType objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Asset objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAssetType(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AssetPeer::addSelectColumns($criteria);
		$startcol = (AssetPeer::NUM_COLUMNS - AssetPeer::NUM_LAZY_LOAD_COLUMNS);
		AssetTypePeer::addSelectColumns($criteria);

		$criteria->addJoin(AssetPeer::ASSET_TYPE_ID, AssetTypePeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AssetPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AssetPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = AssetPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AssetPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = AssetTypePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = AssetTypePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = AssetTypePeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					AssetTypePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Asset) to $obj2 (AssetType)
				$obj2->addAsset($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Asset objects pre-filled with their Category objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Asset objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinCategory(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AssetPeer::addSelectColumns($criteria);
		$startcol = (AssetPeer::NUM_COLUMNS - AssetPeer::NUM_LAZY_LOAD_COLUMNS);
		CategoryPeer::addSelectColumns($criteria);

		$criteria->addJoin(AssetPeer::CATEGORY_ID, CategoryPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AssetPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AssetPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = AssetPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AssetPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = CategoryPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = CategoryPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = CategoryPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					CategoryPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Asset) to $obj2 (Category)
				$obj2->addAsset($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Asset objects pre-filled with their Archive objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Asset objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinArchive(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AssetPeer::addSelectColumns($criteria);
		$startcol = (AssetPeer::NUM_COLUMNS - AssetPeer::NUM_LAZY_LOAD_COLUMNS);
		ArchivePeer::addSelectColumns($criteria);

		$criteria->addJoin(AssetPeer::ARCHIVE_ID, ArchivePeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AssetPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AssetPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = AssetPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AssetPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = ArchivePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = ArchivePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = ArchivePeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					ArchivePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Asset) to $obj2 (Archive)
				$obj2->addAsset($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Asset objects pre-filled with their sfGuardUserProfile objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Asset objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinsfGuardUserProfile(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AssetPeer::addSelectColumns($criteria);
		$startcol = (AssetPeer::NUM_COLUMNS - AssetPeer::NUM_LAZY_LOAD_COLUMNS);
		sfGuardUserProfilePeer::addSelectColumns($criteria);

		$criteria->addJoin(AssetPeer::USER_ID, sfGuardUserProfilePeer::USER_ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AssetPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AssetPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = AssetPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AssetPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = sfGuardUserProfilePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = sfGuardUserProfilePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = sfGuardUserProfilePeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					sfGuardUserProfilePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Asset) to $obj2 (sfGuardUserProfile)
				$obj2->addAsset($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AssetPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AssetPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(AssetPeer::ASSET_TYPE_ID, AssetTypePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::CATEGORY_ID, CategoryPeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::ARCHIVE_ID, ArchivePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::USER_ID, sfGuardUserProfilePeer::USER_ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Asset objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Asset objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AssetPeer::addSelectColumns($criteria);
		$startcol2 = (AssetPeer::NUM_COLUMNS - AssetPeer::NUM_LAZY_LOAD_COLUMNS);

		AssetTypePeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (AssetTypePeer::NUM_COLUMNS - AssetTypePeer::NUM_LAZY_LOAD_COLUMNS);

		CategoryPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (CategoryPeer::NUM_COLUMNS - CategoryPeer::NUM_LAZY_LOAD_COLUMNS);

		ArchivePeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (ArchivePeer::NUM_COLUMNS - ArchivePeer::NUM_LAZY_LOAD_COLUMNS);

		sfGuardUserProfilePeer::addSelectColumns($criteria);
		$startcol6 = $startcol5 + (sfGuardUserProfilePeer::NUM_COLUMNS - sfGuardUserProfilePeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(AssetPeer::ASSET_TYPE_ID, AssetTypePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::CATEGORY_ID, CategoryPeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::ARCHIVE_ID, ArchivePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::USER_ID, sfGuardUserProfilePeer::USER_ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AssetPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AssetPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = AssetPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AssetPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined AssetType rows

			$key2 = AssetTypePeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = AssetTypePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = AssetTypePeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					AssetTypePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Asset) to the collection in $obj2 (AssetType)
				$obj2->addAsset($obj1);
			} // if joined row not null

			// Add objects for joined Category rows

			$key3 = CategoryPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = CategoryPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$cls = CategoryPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					CategoryPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Asset) to the collection in $obj3 (Category)
				$obj3->addAsset($obj1);
			} // if joined row not null

			// Add objects for joined Archive rows

			$key4 = ArchivePeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = ArchivePeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$cls = ArchivePeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					ArchivePeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (Asset) to the collection in $obj4 (Archive)
				$obj4->addAsset($obj1);
			} // if joined row not null

			// Add objects for joined sfGuardUserProfile rows

			$key5 = sfGuardUserProfilePeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = sfGuardUserProfilePeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$cls = sfGuardUserProfilePeer::getOMClass(false);

					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					sfGuardUserProfilePeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (Asset) to the collection in $obj5 (sfGuardUserProfile)
				$obj5->addAsset($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related AssetType table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptAssetType(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AssetPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AssetPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(AssetPeer::CATEGORY_ID, CategoryPeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::ARCHIVE_ID, ArchivePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::USER_ID, sfGuardUserProfilePeer::USER_ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Category table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptCategory(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AssetPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AssetPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(AssetPeer::ASSET_TYPE_ID, AssetTypePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::ARCHIVE_ID, ArchivePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::USER_ID, sfGuardUserProfilePeer::USER_ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Archive table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptArchive(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AssetPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AssetPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(AssetPeer::ASSET_TYPE_ID, AssetTypePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::CATEGORY_ID, CategoryPeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::USER_ID, sfGuardUserProfilePeer::USER_ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related sfGuardUserProfile table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptsfGuardUserProfile(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AssetPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AssetPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(AssetPeer::ASSET_TYPE_ID, AssetTypePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::CATEGORY_ID, CategoryPeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::ARCHIVE_ID, ArchivePeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Asset objects pre-filled with all related objects except AssetType.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Asset objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptAssetType(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AssetPeer::addSelectColumns($criteria);
		$startcol2 = (AssetPeer::NUM_COLUMNS - AssetPeer::NUM_LAZY_LOAD_COLUMNS);

		CategoryPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (CategoryPeer::NUM_COLUMNS - CategoryPeer::NUM_LAZY_LOAD_COLUMNS);

		ArchivePeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (ArchivePeer::NUM_COLUMNS - ArchivePeer::NUM_LAZY_LOAD_COLUMNS);

		sfGuardUserProfilePeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (sfGuardUserProfilePeer::NUM_COLUMNS - sfGuardUserProfilePeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(AssetPeer::CATEGORY_ID, CategoryPeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::ARCHIVE_ID, ArchivePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::USER_ID, sfGuardUserProfilePeer::USER_ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AssetPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AssetPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = AssetPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AssetPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Category rows

				$key2 = CategoryPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CategoryPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = CategoryPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CategoryPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Asset) to the collection in $obj2 (Category)
				$obj2->addAsset($obj1);

			} // if joined row is not null

				// Add objects for joined Archive rows

				$key3 = ArchivePeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ArchivePeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = ArchivePeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ArchivePeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Asset) to the collection in $obj3 (Archive)
				$obj3->addAsset($obj1);

			} // if joined row is not null

				// Add objects for joined sfGuardUserProfile rows

				$key4 = sfGuardUserProfilePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = sfGuardUserProfilePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = sfGuardUserProfilePeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					sfGuardUserProfilePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Asset) to the collection in $obj4 (sfGuardUserProfile)
				$obj4->addAsset($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Asset objects pre-filled with all related objects except Category.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Asset objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptCategory(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AssetPeer::addSelectColumns($criteria);
		$startcol2 = (AssetPeer::NUM_COLUMNS - AssetPeer::NUM_LAZY_LOAD_COLUMNS);

		AssetTypePeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (AssetTypePeer::NUM_COLUMNS - AssetTypePeer::NUM_LAZY_LOAD_COLUMNS);

		ArchivePeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (ArchivePeer::NUM_COLUMNS - ArchivePeer::NUM_LAZY_LOAD_COLUMNS);

		sfGuardUserProfilePeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (sfGuardUserProfilePeer::NUM_COLUMNS - sfGuardUserProfilePeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(AssetPeer::ASSET_TYPE_ID, AssetTypePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::ARCHIVE_ID, ArchivePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::USER_ID, sfGuardUserProfilePeer::USER_ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AssetPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AssetPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = AssetPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AssetPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined AssetType rows

				$key2 = AssetTypePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = AssetTypePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = AssetTypePeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					AssetTypePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Asset) to the collection in $obj2 (AssetType)
				$obj2->addAsset($obj1);

			} // if joined row is not null

				// Add objects for joined Archive rows

				$key3 = ArchivePeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ArchivePeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = ArchivePeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ArchivePeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Asset) to the collection in $obj3 (Archive)
				$obj3->addAsset($obj1);

			} // if joined row is not null

				// Add objects for joined sfGuardUserProfile rows

				$key4 = sfGuardUserProfilePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = sfGuardUserProfilePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = sfGuardUserProfilePeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					sfGuardUserProfilePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Asset) to the collection in $obj4 (sfGuardUserProfile)
				$obj4->addAsset($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Asset objects pre-filled with all related objects except Archive.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Asset objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptArchive(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AssetPeer::addSelectColumns($criteria);
		$startcol2 = (AssetPeer::NUM_COLUMNS - AssetPeer::NUM_LAZY_LOAD_COLUMNS);

		AssetTypePeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (AssetTypePeer::NUM_COLUMNS - AssetTypePeer::NUM_LAZY_LOAD_COLUMNS);

		CategoryPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (CategoryPeer::NUM_COLUMNS - CategoryPeer::NUM_LAZY_LOAD_COLUMNS);

		sfGuardUserProfilePeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (sfGuardUserProfilePeer::NUM_COLUMNS - sfGuardUserProfilePeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(AssetPeer::ASSET_TYPE_ID, AssetTypePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::CATEGORY_ID, CategoryPeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::USER_ID, sfGuardUserProfilePeer::USER_ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AssetPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AssetPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = AssetPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AssetPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined AssetType rows

				$key2 = AssetTypePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = AssetTypePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = AssetTypePeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					AssetTypePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Asset) to the collection in $obj2 (AssetType)
				$obj2->addAsset($obj1);

			} // if joined row is not null

				// Add objects for joined Category rows

				$key3 = CategoryPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = CategoryPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = CategoryPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					CategoryPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Asset) to the collection in $obj3 (Category)
				$obj3->addAsset($obj1);

			} // if joined row is not null

				// Add objects for joined sfGuardUserProfile rows

				$key4 = sfGuardUserProfilePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = sfGuardUserProfilePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = sfGuardUserProfilePeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					sfGuardUserProfilePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Asset) to the collection in $obj4 (sfGuardUserProfile)
				$obj4->addAsset($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Asset objects pre-filled with all related objects except sfGuardUserProfile.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Asset objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptsfGuardUserProfile(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AssetPeer::addSelectColumns($criteria);
		$startcol2 = (AssetPeer::NUM_COLUMNS - AssetPeer::NUM_LAZY_LOAD_COLUMNS);

		AssetTypePeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (AssetTypePeer::NUM_COLUMNS - AssetTypePeer::NUM_LAZY_LOAD_COLUMNS);

		CategoryPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (CategoryPeer::NUM_COLUMNS - CategoryPeer::NUM_LAZY_LOAD_COLUMNS);

		ArchivePeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (ArchivePeer::NUM_COLUMNS - ArchivePeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(AssetPeer::ASSET_TYPE_ID, AssetTypePeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::CATEGORY_ID, CategoryPeer::ID, $join_behavior);

		$criteria->addJoin(AssetPeer::ARCHIVE_ID, ArchivePeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAssetPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AssetPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AssetPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = AssetPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AssetPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined AssetType rows

				$key2 = AssetTypePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = AssetTypePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = AssetTypePeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					AssetTypePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Asset) to the collection in $obj2 (AssetType)
				$obj2->addAsset($obj1);

			} // if joined row is not null

				// Add objects for joined Category rows

				$key3 = CategoryPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = CategoryPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = CategoryPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					CategoryPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Asset) to the collection in $obj3 (Category)
				$obj3->addAsset($obj1);

			} // if joined row is not null

				// Add objects for joined Archive rows

				$key4 = ArchivePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = ArchivePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = ArchivePeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					ArchivePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Asset) to the collection in $obj4 (Archive)
				$obj4->addAsset($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseAssetPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseAssetPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new AssetTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? AssetPeer::CLASS_DEFAULT : AssetPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a Asset or Criteria object.
	 *
	 * @param      mixed $values Criteria or Asset object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAssetPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseAssetPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Asset object
		}

		if ($criteria->containsKey(AssetPeer::ID) && $criteria->keyContainsValue(AssetPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.AssetPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAssetPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseAssetPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Asset or Criteria object.
	 *
	 * @param      mixed $values Criteria or Asset object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAssetPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseAssetPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(AssetPeer::ID);
			$selectCriteria->add(AssetPeer::ID, $criteria->remove(AssetPeer::ID), $comparison);

		} else { // $values is Asset object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAssetPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseAssetPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the asset table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(AssetPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			AssetPeer::clearInstancePool();
			AssetPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Asset or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Asset object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			AssetPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Asset) {
			// invalidate the cache for this single object
			AssetPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(AssetPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				AssetPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			AssetPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Asset object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Asset $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Asset $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(AssetPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(AssetPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(AssetPeer::DATABASE_NAME, AssetPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Asset
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = AssetPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(AssetPeer::DATABASE_NAME);
		$criteria->add(AssetPeer::ID, $pk);

		$v = AssetPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AssetPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(AssetPeer::DATABASE_NAME);
			$criteria->add(AssetPeer::ID, $pks, Criteria::IN);
			$objs = AssetPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array(array('slug'));
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseAssetPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseAssetPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseAssetPeer::buildTableMap();

