generator:
  class: sfPropelGenerator
  param:
    model_class:           AccessLogEvent
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              AccessLogEvent
    plural:                AccessLogEvents
    route_prefix:          access_log_event
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display:           [Asset, sfGuardUserProfile, Created_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
