<?php

require 'lib/model/om/BaseAssetPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'asset' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Feb  3 19:07:27 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AssetPeer extends BaseAssetPeer {

} // AssetPeer
