<?php

require 'lib/model/om/BaseAudioAsset.php';


/**
 * Skeleton subclass for representing a row from the 'audio_asset' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Feb  8 22:36:16 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AudioAsset extends BaseAudioAsset {

} // AudioAsset
