<?php

require 'lib/model/om/BaseBinderPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'binder' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Mar 12 22:47:42 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BinderPeer extends BaseBinderPeer {

  public static function retrieveByUserId($user_id)
  {
    $c = new Criteria();
    $c->add(BinderPeer::USER_ID, $user_id);
    return BinderPeer::doSelect($c);
  }
  
  
  public static function retrieveByNotes($text)
  {
    $c = new Criteria();
    $c->add(BinderPeer::NOTES, '%' . $text .'%', Criteria::LIKE);
    return BinderPeer::doSelect($c);
  }

} // BinderPeer
