<?php

require 'lib/model/om/BaseBinderUserPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'binder_user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Mar 19 16:39:54 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BinderUserPeer extends BaseBinderUserPeer {

} // BinderUserPeer
