<?php

require 'lib/model/om/BaseDescription.php';


/**
 * Skeleton subclass for representing a row from the 'description' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Jan  8 17:21:38 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Description extends BaseDescription {

} // Description
