<?php

require 'lib/model/om/BasePictureAssetPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'picture_asset' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Feb  8 22:36:15 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PictureAssetPeer extends BasePictureAssetPeer {

} // PictureAssetPeer
