<?php

require 'lib/model/om/BaseSourcePeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'source' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat May  1 15:17:57 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SourcePeer extends BaseSourcePeer {

} // SourcePeer
