<?php

require 'lib/model/om/BaseSourcePeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'source' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat May  1 15:17:57 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SourcePeer extends BaseSourcePeer {

  const
    STATUS_READY = 1,
    STATUS_EMAILSENT = 2,
    STATUS_SCHEDULED = 3
    ;
    
  public static function getStatusDescription($status)
  {
    $statuses=array(
      self::STATUS_READY => 'Ready',
      self::STATUS_EMAILSENT => 'Email sent',
      self::STATUS_SCHEDULED => 'Scheduled',
      );
    return $statuses[$status];
    
  }
  
  public static function retrieveByTasklogEvent($id)
  {
    $c = new Criteria();
    $c->add(SourcePeer::TASK_LOG_EVENT_ID, $id);
    $c->clearSelectColumns();
    $c->addGroupByColumn(SourcePeer::USER_ID);
    $c->addAsColumn('USER_ID', 'MIN(' . SourcePeer::USER_ID . ')');
    return SourcePeer::doSelect($c);
  }
  
  public static function retrieveByPathAndBasename($path, $basename)
  {
    $c = new Criteria();
    $c->add(SourcePeer::RELATIVE_PATH, $path);
    $c->add(SourcePeer::BASENAME, $basename);
    return SourcePeer::doSelectOne($c);
  }

} // SourcePeer
