<?php

require 'lib/model/om/BaseTaskLogPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'task_log' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Feb  3 19:07:28 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TaskLogPeer extends BaseTaskLogPeer {

} // TaskLogPeer
