<?php

require 'lib/model/om/BaseVideoAsset.php';


/**
 * Skeleton subclass for representing a row from the 'video_asset' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Feb  8 22:36:15 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class VideoAsset extends BaseVideoAsset {
	
	protected
		$_slug,
		$_assetFile;

	public function getVideo()
	{
		$this->_slug=$this->getAsset()->getSlug();
		$this->_assetFile=new VideoFile($this->_slug);
		return $this->_assetFile;
	}


} // VideoAsset
