generator:
  class: sfPropelGenerator
  param:
    model_class:           AssetType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              AssetType
    plural:                AssetTypes
    route_prefix:          asset_type
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
