propel:

  sf_guard_user_profile:
    _attributes:  { phpName: sfGuardUserProfile }
    user_id:      { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onUpdate: cascade, onDelete: cascade, primaryKey: true }
    first_name:   varchar(50)
    last_name:   varchar(50)

  picture:
    id: ~
    path: varchar(255)

  description:
    id: ~
    picture_id: ~
    text: varchar(255)
