default:
  http_metas:
    content-type: text/html

  metas:
    title:   WVIOLA
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, flowplayer.css, /sfPropelPlugin/css/global.css, /sfPropelPlugin/css/default.css ]

  javascripts:    []

  has_layout:     true
  layout:         layout
