asset_search:
  url: /search
  param: { module: asset, action: search }

asset_empty_advancedsearch:
  url: /advancedsearch
  param: { module: asset, action: advancedsearch }

asset_filled_advancedsearch:
  url: /advancedsearch/query/:query
  param: { module: asset, action: advancedsearch }

showpicture:
  url: /asset/showpicture/album/:album/number/:number.:sf_format 
  param: { module: asset, action: showpicture }
  requirements:
    sf_format: jpeg
    sf_method: get

sourcethumbnail:
  url:   /filebrowser/thumbnail/path/:path/basename/:basename/number/:number.:sf_format
  param: { module: filebrowser, action: thumbnail }
  requirements:
    sf_format: jpeg
    sf_method: get

thumbnail:
  url:   /asset/thumbnail/:id.:sf_format
  param: { module: asset, action: thumbnail }
  requirements:
    sf_format: jpeg
    sf_method: get

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
 
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

profile:
  url:  /profile
  param: { module: profile, action: index }  

# default rules
homepage:
  url:   /
  param: { module: welcome, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*


