all:
  config:
    organization: My Organization Name
    website: http://www.wviola.net.localhost

  sf_guard_plugin:
    check_password_callable: [Authentication, testOnly]

  authentication:
    ldap_host: ldaps://ldap.sv.lnf.it ldaps://ldap2.sv.lnf.it
    ldap_domain: dc=sv,dc=lnf,dc=it
    ldap_users: ou=People
    ldap_groups: ou=Group
    ldap_userattribute_username: uid
    ldap_userattribute_email: mail
    ldap_userattribute_firstname:
    ldap_userattribute_lastname: displayname
    ldap_groupattribute_cn: cn
    ldap_groupattribute_members: memberuid
    guardgroup_admin: [ ced ]
    guardgroup_asset_encoders: [ riabili, tecla ]
    guardgroup_asset_viewers: [ medici, dirsan, dirsci ]
    

