propel:

  sf_guard_user_profile:
    _attributes:  { phpName: sfGuardUserProfile }
    user_id:      { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onUpdate: cascade, onDelete: cascade, primaryKey: true }
    first_name:   varchar(50)
    last_name:   varchar(50)
    imported_at: timestamp

  asset:
    id: ~
    slug: { type: varchar(50), required: true, index: unique }
    status: integer
    archive_id: ~
    asset_type: integer
    assigned_title: varchar(255)
    category_id: ~
    notes: longvarchar
    event_date: date
    source_filename: varchar(255)
    source_file_date: date
    highquality_md5sum: varchar(32)
    lowquality_md5sum: varchar(32)
    has_thumbnail: boolean
    thumbnail_width: integer
    thumbnail_height: integer
    thumbnail_size: integer
    user_id:  { type: integer, foreignTable: sf_guard_user_profile, foreignReference: user_id, required: true, onUpdate: cascade, onDelete: cascade}
    created_at: ~
    updated_at: ~

  video_asset:
    asset_id: { type: integer, foreignTable: asset, foreignReference: id, required: true, onUpdate: cascade, onDelete: cascade, primaryKey: true }
    duration: float
    highquality_width: integer
    highquality_height: integer
    highquality_video_codec: varchar(20)
    highquality_audio_codec: varchar(20)
    highquality_frame_rate: integer
    highquality_aspect_ratio: float
    lowquality_width: integer
    lowquality_height: integer
    lowquality_video_codec: varchar(20)
    lowquality_audio_codec: varchar(20)
    lowquality_frame_rate: integer

  picture_asset:
    asset_id: { type: integer, foreignTable: asset, foreignReference: id, required: true, onUpdate: cascade, onDelete: cascade, primaryKey: true }
    highquality_width: integer
    highquality_height: integer
    highquality_picture_format: varchar(10)
    lowquality_width: integer
    lowquality_height: integer
    lowquality_picture_format: varchar(10)

  photoalbum_asset:
    asset_id: { type: integer, foreignTable: asset, foreignReference: id, required: true, onUpdate: cascade, onDelete: cascade, primaryKey: true }
    pictures_count: integer

  audio_asset:
    asset_id: { type: integer, foreignTable: asset, foreignReference: id, required: true, onUpdate: cascade, onDelete: cascade, primaryKey: true }
    duration: float
    highquality_audio_codec: varchar(10)
    lowquality_audio_codec: varchar(10)

  archive:
    id:  ~
    slug: varchar(50)
    created_at: ~
    burned_at: timestamp
    user_id:  { type: integer, foreignTable: sf_guard_user_profile, foreignReference: user_id, required: false, onUpdate: cascade, onDelete: cascade}
    md5sum: varchar(32)

  category:
    id: ~
    shortcut: { type: varchar(5), index: unique }
    name: varchar(50)

  access_log:
    id: ~  
    asset_id:  ~
    user_id:      { type: integer, foreignTable: sf_guard_user_profile, foreignReference: user_id, required: true, onUpdate: cascade, onDelete: restrict }
    created_at: ~

  task_log:
    id: ~
    task_name: varchar(50)
    options: longvarchar
    arguments: longvarchar
    started_at: timestamp
    finished_at: timestamp
